### ISSUE TITLE
Maian raw scan output has unparsed color codes

### ISSUE THREAD

**Issue by thedarkspy** [cibr-qcri/kansa#203]
**Describe the bug**
Maian raw scan output has unparsed color codes that are supposed to display the result in different colors for different lines.

**To Reproduce**
1. Go to any contract that has Maian raw scan
2. Check the Scan tab
3. Choose Maian
4. Notice the unparsed codes in the output

**Expected behavior**
Output should be colored according to the ANSI color codes embedded in the raw scan.

**Comment by boshmaf** [comment]
To be fixed in #199.
