### ISSUE TITLE
Some contracts have invalid solidity version value with parsing errors

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/kansa#35]
**Describe the bug**
When viewing some contracts (e.g., https://kansa.cibr.qcri.org/contract/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2), Solidity version is shown as -1 and the metadata/creation tx are shown as N/A and parsed as such, resulting in invalid API requests.

**To Reproduce**
1. Go to contract 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2
2. See errors

**Expected behavior**
If solidity version not available, it should show N/A, same for the metadata. N/A must never be linked.

**Screenshots**
![Screen Shot 2022-09-19 at 9 13 52 PM](https://user-images.githubusercontent.com/3311191/191085660-304c10e1-542e-4d5d-a50c-522f88b737cf.png)

**Comment by thedarkspy** [comment]
This issue seems to be related to DeFi protocols specifically. Their `eth_enrich_contract` table is incomplete. 

CC: @sajithaliyanage

**Comment by thedarkspy** [comment]
So we found out that these happen with contracts that have no bytecode (either NULL or 0x). Most likely these contracts were destructed.

**Comment by thedarkspy** [comment]
Closed by #66
