### ISSUE TITLE
Internal txes show duplicates

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/kansa#63]
**Describe the bug**
When a contract appears as both From and To, it is shown multiple times (one from From, and one from To).

**Comment by sajithaliyanage** [comment]
Closing this issue since the [UNION](https://www.techonthenet.com/postgresql/union.php#:~:text=The%20PostgreSQL%20UNION%20operator%20is,sets%20with%20similar%20data%20types.) operator removes duplicate rows between the various SELECT statements.
