### ISSUE TITLE
Decompiled code has logs entries after source code 

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/kansa#81]
**Describe the bug**
When browsing through the decompiled bytecode (intermediary language), you can see decompiler logs at the end of the code, which is not part of the code.

**To Reproduce**
1. Go to any contract with a byecode
2. Click on Code then select Decompiled
3. Scroll down to the bottom

**Expected behavior**
No log outputs included.

**Screenshots**
<img width="1103" alt="Screen Shot 2022-10-02 at 12 07 41 PM" src="https://user-images.githubusercontent.com/3311191/193446809-f3bfa3f6-f88a-4994-b7ed-8ecd20781f62.png">

**Comment by sajithaliyanage** [comment]
Use `--silent` attribute with the panoramix command.

**Comment by sajithaliyanage** [comment]
Related commit: https://github.com/cibr-qcri/airflow-tasks/commit/54089dcd39fadde4bb801f6b80b5ef0d4515cc86
